language: java

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: fluid
    token:
      secure: "dyAzbLPkHKoYcGVKeHDdX4bq2Oz2moluhCw0yvuSwS8xZWTuqsrB3ncUvEmyNGpk/zzC4ldkRxrzG5oNDEv7bnJhypNlMqNpHfeCX+TW6Bafue+00h59aBwqpXGFtPN5PxanJL7A/fm+QDBNJORu9n6zHvl4jbbZcIn3g904t9zavDehi1eF/R4m0YN6tVZuPLarg2p1vI2lGTDVAHDduZiZDb2tiIQgQ2elfedeRTzb9tvzrvPMbxYvEu0u2o936subQkYWu231qcbbVaJiWMGKXWKyeJZC9ynYORsuKqgPNY+jBCPYSEzPDyCXVi7h1o9dfErMTyklsHKNQ8WtOTyNe+fun1T+jcJ8KonsWpZB6knMaDKF/eldCRmg4Ma2Q2sgkVe5g892U1k/gekdcfO7GcYGPD9xFkPlgwjCJt0khhRHUphH5r7wndsOC9B07zOyJbLOtVn49GRrBTqH6Ins6qVfhOBP7bVPWkhsMoPzCO0Bl26lpSoxz+G/a+mcBbjmVTCs+jKQbqN+SsdtkZGevSp7xOUhUi3OGIm0StxpbywiFSJZtCXZ5+FPqrP7XMSM+OqSLGiovoSle3z/qmkgCizxKCoEo6MwLgzq01Owep+rmNXaMZvhmtJDDpPfReRNIldCQdk4YoaUF6PVw66NggoOQYkgNCeMWRCCtdQ="

env:
  global:
    - SONATYPE_USERNAME="clement.escoffier"
    - secure: "1aWBp7FWqUzB+nL3IzpZonyD4S+DjrQJk2ylh+i0GSAjXyS2ZKEzu61Ho5MRP8TqeUp4Nbqa8wgas8N8Ep7/jEYAlfkmCZI0SzqpezDPBzEYF8kn0VTs2C8cKunE2GCCEFa5IIYKuIRfTBvBu77xCt2mCEKNHYsw6670aT/wAVoE7KdwwPZRNoQ27Y5W3Py4fS53ecIUgimHtGNb1+FRvWKxncVBlojerzvl63hU/tqb3WrjqPIymBN6t4I0x5rTXhkbjShKsaQ5WFXghaOt26+2UKpfA8Bhc8YUZ5I64fam63xGkfY3nGZC/xyfbtPCTN4kEqhb5VfK6bxjS4/2tuIpkS8hfo8YFXaO3e/pgVXXIPeMXcrfoy14O22dBgbkypoHGBXVvw/3muDLAOn2WbVbnHD7KMTuhev3NzNbHuiPwIWqXQ/6fgPSEysMWUlS3+h352NJlw4GMjhEtH0nI3Uk3w4aEYRFWrfiNa40Y6OpDciQ5GI5mj0FZYBBPRm5u4HvatQHtKndyWVl82zyouoHS6/xj4Ig+g1irS0GMir+PsAP5ln8UmJm1z/ZFkHasC+mY6+MGQnZy06TKm6E6xFuCwWMzH0Fu+m5evOgHudtpbBIYhhmdbZ/BcBHKghiipUJpsMHy8CvhhUfewLL5Bz6B2XgNQlP+UUji+cf72c="

script:
  - mvn clean install sonar:sonar -Pcoverage

after_success:
    - bash <(curl -s https://codecov.io/bash)
    - .build/deploy-snapshot.sh

notifications:
  email:
    - clement@apache.org
    - hekonsek@gmail.com
